[package]
authors = ["@colinnielsen"]
compiler_version = "0.10.1"
name = "ecrecover"
notes = "AMDG"
type = "lib"

[dependencies]
array_helpers = { tag = "v0.16.0", git = "https://github.com/signorecello/noir-array-helpers" }
